name: CI

on: pull_request

jobs:
  defaults:
    runs-on: ubuntu-latest

  title:
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '[a-z]+(\([a-z]+\))?:.*'
          allowed_prefixes: 'chore,fix,feat,perf'
          prefix_case_sensitive: false
          min_length: 10
          max_length: 100

  lint:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn lint

  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn test
